filetype plugin indent on
syntax on

set hlsearch
set incsearch
set number
set relativenumber
set hidden
set ruler
set list
set listchars=trail:-,tab:\ \
set expandtab
set autoindent
set nowrap
set laststatus=2
set wildmenu
set noswapfile
set viminfofile=NONE

nnoremap <Space> :ls<CR>:b<Space>
